version: "3.6"

services:
  metabase:
    image: metabase/metabase:v0.32.1
    expose:
      - 3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_TIMEZONE: Europe/Paris
    volumes:
      - /metabase-data

  mongo:
    image: mongo:3.6
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./dumps:/dumps
      - ./mongo-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: bash -c "</dev/tcp/127.0.0.1/27017"

  mongoclient:
    image: mongoclient/mongoclient:latest
    expose: 
      - 3000
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://mongo:27017/test
      STARTUP_DELAY: 20
    stop_signal: SIGKILL